export {default as Header} from "./header/Header"
export {default as Footer} from "./footer/Footer"
export {default as Home} from "./home/Home"
export {default as MovieCard} from "./movieCard/MovieCard"
export {default as MovieDetail} from "./movieDetail/MovieDetail"
export {default as MovieListing} from "./movieListing/MovieListing"
export {default as PageNotFound} from "./pageNotFound/PageNotFound"